### PR TITLE
hide token holder count when not consolidating

### LINKED ISSUE #963: Token holders count is always 0 on ETH Mainnet
Token holders count is always 0 on ETH Mainnet. Possibly, this is due to a query taking too much time to run while trying to get the counts.

### Environment

- Tested on BlockScout's Production Environment.

### Steps to reproduce

- Visit any token details page in the production environment. For instance: https://blockscout.com/eth/mainnet/tokens/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359

### Expected behavior

- The `addresses` value should be the count of token holders for that token.

### Actual behaviour

- The `addresses` value is always zero.

### PR DESCRIPTION
**Pull request by GuSilverFlame**
closes #963 (not a full solution, just a way to quickly enhance user experiance a little)
### Enhancements
* hide token holders count when consolidation config is set to false
  * disabled example:
    `config :explorer, Explorer.Counters.TokenHoldersCounter, enable_consolidation: false`
  * enabled example:
    `config :explorer, Explorer.Counters.TokenHoldersCounter, enable_consolidation: true`

### Screenshots
config set to true(nothing changes):
config on

config set to false(the address count disappears):
config off

### CODE REVIEW

File: apps/explorer/lib/explorer/counters/token_holders_counter.ex [hunk 1]
```diff
@@ -10,6 +10,11 @@ defmodule Explorer.Counters.TokenHoldersCounter do
 
   @table :token_holders_counter
 
+  # It is undesirable to automatically start the consolidation in all environments.
+  # Consider the test environment: if the consolidation initiates but does not
+  # finish before a test ends, that test will fail. This way, hundreds of
+  # tests were failing before disabling the consolidation and the scheduler in
+  # the test env.
   config = Application.get_env(:explorer, Explorer.Counters.TokenHoldersCounter)
```
Comment (feliperenan) [inline apps/explorer/lib/explorer/counters/token_holders_counter.ex]: Using this config here as `module_attribute` we need to recompile the application case we change this config. Is that what we want to?

cc @Lucasnar

Comment (Lucasnar) [reply apps/explorer/lib/explorer/counters/token_holders_counter.ex]: We didn't see the need of changing this config after the app was up, so it was better to calculate it only once, instead of calculating it every time we wanted to know whether or not consolidation was enabled. I'm not sure how we would change this without recompiling the application (we would have to log into the machine, spawn an iex there and change the environment, right?).

Comment (GuSilverFlame) [reply apps/explorer/lib/explorer/counters/token_holders_counter.ex]: makes sense 🤔

**Comment by acravenho** [comment]
@GuSilverFlame I'm receiving this error when I change `config :explorer, Explorer.Counters.TokenTransferCounter` to `false` and `config :explorer, Explorer.Counters.TokenHoldersCounter` to `false`

```
11:05:56.490 [error] #PID<0.2183.0> running BlockScoutWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /tokens/0x24a90f96747941ea47c105fce71cca3704eec45e/token_transfers
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(:token_transfer_counter, "0x24a90f96747941ea47c105fce71cca3704eec45e")
        (explorer) lib/explorer/counters/token_transfer_counter.ex:66: Explorer.Counters.TokenTransferCounter.fetch/1
        (block_scout_web) lib/block_scout_web/controllers/tokens/transfer_controller.ex:20: BlockScoutWeb.Tokens.TransferController.index/2
        (block_scout_web) lib/block_scout_web/controllers/tokens/transfer_controller.ex:1: BlockScoutWeb.Tokens.TransferController.action/2
        (block_scout_web) lib/block_scout_web/controllers/tokens/transfer_controller.ex:1: BlockScoutWeb.Tokens.TransferController.phoenix_controller_pipeline/2
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web) lib/plug/debugger.ex:99: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/andrew/Documents/GitHub/poanetwork/pullrequests/blockscout/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by GuSilverFlame** [comment]
@acravenho sorry, I left the config explanation a little vague
you only set to false the `enable_consolidation` part, but leave the `enabled` config still on true(this one tries to replace the cached count by a query on the database, turning it off could be even worse on the mainnet)

**Comment by Lucasnar** [comment]
@acravenho and @GuSilverFlame, isn't this PR only about `Explorer.Counters.TokenHoldersCounter`? If yes, I think disabling `Explorer.Counters.TokenTransferCounter` is actually expected to trigger a lot of errors, as we are not disabling other parts of the application to try to access the `TokenTransferCounter`.

**Comment by GuSilverFlame** [comment]
@Lucasnar yes it is about disabling the consolidation, that config is only on the `TokenHoldersCounter `, adding `enable_consolidation: false` to `TokenTransferCounter` will do nothing, neither break nor have any positive effect

File: apps/explorer/lib/explorer/counters/token_holders_counter.ex [hunk 2]
```diff
@@ -94,15 +99,17 @@ defmodule Explorer.Counters.TokenHoldersCounter do
...
+  In order to choose whether or not to enable the scheduler and the initial
+  consolidation, change the following Explorer config:
+
+  `config :explorer, Explorer.Counters.TokenHoldersCounter, enable_consolidation: true`
+
+  to:
+
+  `config :explorer, Explorer.Counters.TokenHoldersCounter, enable_consolidation: false`
+  """
+  def enable_consolidation?, do: @enable_consolidation
```
Comment (amandasposito) [inline apps/explorer/lib/explorer/counters/token_holders_counter.ex]: WDYT of writing a test for this?

Comment (GuSilverFlame) [reply apps/explorer/lib/explorer/counters/token_holders_counter.ex]: kinda hard, on test environment it always returns `false` nothing else, no way to test a fail case or a case it returns true....
