### PR TITLE
Increase Indexer.TokenBalance.Fetcher timeout and add treatment error

### LINKED ISSUE #698: Indexer.TokenBalanceFetcher Ecto.Association.NotLoaded
The error.log file is filled with these errors after my deployment tonight.
```
04:20:01.092 [error] Task #PID<0.13677.6> started from #PID<0.13236.6> terminating
** (stop) exited in: GenServer.call(Indexer.TokenBalanceFetcher, {:buffer, [%Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<1, 212, 235, 211, 80, 153, 54, 137, 128, 9, 110, 103, 227, 153, 74, 222, 88, 98, 94, 181>>}, block_number: 8518302, id: 220164, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<4, 181, 255, 59, 175, 35, 249, 190, 42, 147, 8, 178, 51, 111, 27, 233, 76, 27, 240, 134>>}, block_number: 8518310, id: 220165, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<28, 92, 98, 82, 97, 14, 11, 170, 69, 234, 59, 34, 79, 221, 23, 196, 52, 18, 30, 251>>}, block_number: 8518306, id: 220166, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<68, 254, 37, 55, 190, 83, 21, 77, 72, 124, 252, 23, 241, 167, 178, 147, 231, 217, 84, 196>>}, block_number: 8518310, id: 220167, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<76, 76, 241, 32, 137, 108, 63, 2, 62, 54, 246, 23, 166, 178, 194, 145, 69, 45, 114, 56>>}, block_number: 8518305, id: 220168, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<123, 95, 82, 194, 158, 60, 36, 4, 203, 246, 190, 65, 126, 3, 137, 192, 219, 177, 146, 95>>}, block_number: 8518302, id: 220169, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<140, 187, 120, 27, 184, 79, 28, 131, 115, 88, 164, 131, 164, 115, 159, 168, 163, 67, 145, 252>>}, block_number: 8518304, id: 220170, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<154, 25, 216, 65, 23, 30, 118, 33, 95, 160, 50, 254, 92, 225, 151, 134, 148, 200, 162, 53>>}, block_number: 8518303, id: 220171, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<173, 232, 224, 4, 134, 173, 184, 7, 243, 202, 253, 168, 77, 71, 101, 11, 7, 215, 87, 131>>}, block_number: 8518302, id: 220172, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<173, 232, 224, 4, 134, 173, 184, 7, 243, 202, 253, 168, 77, 71, 101, 11, 7, 215, 87, 131>>}, block_number: 8518303, id: 220173, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>}, updated_at: ~N[2018-09-11 04:19:54.954851], value: nil, value_fetched_at: nil}, %Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<173, 232, 224, 4, 134, 173, 184, 7, 243, 202, 253, 168, 77, 71, 101, 11, 7, 215, 87, 131>>}, block_number: 8518304, id: 220174, inserted_at: ~N[2018-09-11 04:19:54.954851], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<186, 132, 229, 70, 118, 171, 220, 37, 220, 179, 60, 123, 14, 31, 37, 251, 56, 212, 117, 8>>} (truncated)
```

### Environment

* Operating System: Linux

### Steps to reproduce

1. Index Kovan

### Expected behaviour

n/a

### Actual behaviour

n/a

### PR DESCRIPTION
**Pull request by amandasposito**
Resolves #698

## Motivation

The `Indexer.TokenBalance.Fetcher` was being shut down when importing lots of token balances.

```
04:20:01.092 [error] Task #PID<0.13677.6> started from #PID<0.13236.6> terminating
** (stop) exited in: GenServer.call(Indexer.TokenBalanceFetcher, {:buffer, [ ... (truncated)
```

It was also raising an exception when the `Chain.import` returned an empty list.

```
`** (MatchError) no match of right hand side value: {:ok, %{token_balances: []}}`
```

### Bug Fixes

* Increase the `timeout` used by the `GenServer.call` at the `BufferedTask.buffer` so it doesn't exit when the token balances list is too long.
* Add `error` treatment when something unexpected happens with the `Chain.import` at the `Indexer.TokenBalance.Fetcher`

### CODE REVIEW

File: apps/indexer/lib/indexer/token_balance/fetcher.ex [hunk 1]
```diff
@@ -51,14 +54,38 @@ defmodule Indexer.TokenBalance.Fetcher do
...
       |> Stream.map(&format_params/1)
       |> TokenBalances.fetch_token_balances_from_blockchain()
 
-    {:ok, %{token_balances: [_]}} = Chain.import(%{token_balances: %{params: token_balances_params}})
+    token_balances_params
+  end
 
-    :ok
+  def import_token_balances(token_balances_params) do
+    with {:ok, _} <- Chain.import(%{token_balances: %{params: token_balances_params}}) do
```
Comment (igorffs) [inline apps/indexer/lib/indexer/token_balance/fetcher.ex]: We could use `case` instead of `with` here 🙌

**Comment by acravenho** [comment]
Hey @amandasposito 

I'm still receiving these types of errors when deploying this fix to ETH mainnet:

```
05:44:59.158 [error] Task #PID<0.11458.8> started from Indexer.TokenBalance.Fetcher terminating
** (stop) exited in: :gen_server.call(Explorer.Repo.Pool, {:checkout, #Reference<0.366696268.3731619841.152500>, true}, 5000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:223: :gen_server.call/3
    (poolboy) src/poolboy.erl:55: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:928: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:750: DBConnection.run/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:205: Explorer.Chain.Import.all/1
Function: &Indexer.TokenBalance.Fetcher.run/3
    Args: [[%Explorer.Chain.Address.TokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 6094583, id: 25123429, inserted_at: ~N[2018-09-08 03:47:17.204862], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<93, 72, 172, 163, 149, 77, 40, 138, 95, 234, 159, 195, 116, 172, 72, 165, 219, 245, 250, 109>>}, updated_at: ~N[2018-09-08 03:47:17.204862], value: nil, value_fetched_at: nil}], 0, [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "**readacted**", method_to_url: [eth_getBalance: "**redacted**", trace_replayTransaction: "**redacted**"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity]]
```
