### PR TITLE
Script to fix address_current_token_balances

### LINKED ISSUE #1317: Token Balance Fetcher did not insert the highest block number balance some time in the past
This is a partial table of the `address_token_balances` for `address_hash`  0x9a4a90e2732f3fa4087b0bb4bf85c76d14833df1 and `token_contract_address_hash` 0x97aeb5066e1a590e868b511457beb6fe99d329f5.

| Block Number  | Balance | `value_fetched_at` |
| ------------- | ------------- | ------------- |
| 6200506 | 0 |	2019-01-05 06:46:03 |
| 6372464 | 61750000000000000000000 | 2019-01-05 01:10:42 |
| 6434589 | 85490000000000000000000 | 2018-10-08 23:08:37 |

This is the `address_current_token_balances` table which should display the balance from block number `6434589`. Instead, it's showing the balance of block `6372464`

| Block Number  | Balance | `value_fetched_at` |
| ------------- | ------------- | ------------- |
| 6372464 | 61750000000000000000000 | 2019-01-05 01:10:42 |	

### Environment

* Chain: Mainnet

### Steps to reproduce

If the catchup indexer views a token balance from the past, it's not checking that this balance is from the highest block number. Instead, it's overwriting the value of the `address_current_token_balances` table regardless if it's the highest block number.

### Expected behaviour

The `address_current_token_balances` table should show the highest block number for the `address_hash` and `token_contract_address_hash`.

### Actual behaviour

No matter the block number, any fetcher can update the value of the current token balance table.

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #1317

### Enhancements
* Additional tests to check #1317 is not reproducible in the current code base.

### Bug Fixes
* Some bug in the past caused `address_current_token_balances` to not always be up-to-date.  The verifier below show the number of incorrect `address_current_token_balances` not growing, so the bug itself is fixed, but the data is still wrong and need to be updated.

  Run `apps/explorer/priv/repo/migrations/scripts/update_address_current_token_balances_in_batches.sql` to fix any `address_current_token_balances` that have the incorrect `block_number` or `value`.

  Run the following to verify everything is fixed:

  ```sql
  SELECT COUNT(*)
  FROM (SELECT 1
        FROM address_token_balances
               INNER JOIN address_current_token_balances
                          ON address_current_token_balances.address_hash = 
  address_token_balances.address_hash AND
                             address_current_token_balances.token_contract_address_hash =
                             address_token_balances.token_contract_address_hash
        GROUP BY address_token_balances.address_hash,
                 address_token_balances.token_contract_address_hash,
                 address_current_token_balances.block_number
        HAVING MAX(address_token_balances.block_number) !=
               address_current_token_balances.block_number) AS address_incorrect_token_balances;
  ```

  Which should return `0`. after the script is run.  
  **WARNING:** the check SQL above will take 15-20 minutes on Eth Mainnet.

## Upgrading

See Bug Fixes above.

### CODE REVIEW

File: apps/explorer/priv/repo/migrations/scripts/update_address_current_token_balances_in_batches.sql [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+    WHERE value IS NOT NULL
+    ORDER BY address_hash, token_contract_address_hash;
+
+    row_count := (SELECT COUNT(*) FROM address_token_temp);
+    RAISE NOTICE '% items to be updated', row_count;
+
+    -- ITERATES THROUGH THE ITEMS UNTIL THE TEMP TABLE IS EMPTY
+    WHILE row_count > 0
+      LOOP
+        UPDATE address_current_token_balances
```
Comment (KronicDeth) [inline apps/explorer/priv/repo/migrations/scripts/update_address_current_token_balances_in_batches.sql]: This is based on

https://github.com/poanetwork/blockscout/blob/8718ca40699161c420ea3d95a742f75b05ae8872/apps/explorer/lib/explorer/chain/import/runner/blocks.ex#L382-L435

but as an `UPDATE` instead of an `INSERT`.
