### PR TITLE
Decrease BlockScoutWeb.EventHandler message queue

### LINKED ISSUE #1243: BlockScoutWeb.EventHandler.init/1 receiving thousands of messages
During and after indexing `BlockScoutWeb.EventHandler.init/1` is receiving a large number of messages from what looks like both the realtime and catchup indexer. We should only be sending messages from the realtime indexer. 

screen shot 2018-12-17 at 3 00 45 pm

### Environment

* Operating System: Mac

### Steps to reproduce

1. Start the indexer
2. Navigate to Wobserver
3. View the highest Message Queue

### Expected behaviour

Only receive broadcast messages from the realtime indexer.

### Actual behaviour

Receiving messages from both the catchup and realtime indexers.

### PR DESCRIPTION
**Pull request by amandasposito**
Resolves #1243

## Motivation

During and after indexing `BlockScoutWeb.EventHandler.init/1` is receiving a large number of messages from what looks like both the `realtime` and `catchup` indexer. 

From time to time, the messages get stuck in the `GenServer` in the `prim_inet.recv0/3` function probably waiting for the database.

screen shot 2018-12-19 at 17 58 32

### Enhancements
* Removed unused event that was being broadcast.
* Only broadcast :realtime events.
* Refactor events broadcast and subscribing.

### CODE REVIEW

**Comment by acravenho** [comment]
@amandasposito Do you have some ideas to fix the message queue getting overloaded? I'm unsure what to do next here.

File: apps/explorer/test/explorer/chain_test.exs [hunk 1]
```diff
@@ -22,6 +22,7 @@ defmodule Explorer.ChainTest do
     Wei
   }
 
+  alias Explorer.Chain.Events.Subscriber
```
Comment (GuSilverFlame) [inline apps/explorer/test/explorer/chain_test.exs]: this alias doesn't seem to be used here, is it necessary?

Comment (amandasposito) [reply apps/explorer/test/explorer/chain_test.exs]: It was a leftover, I removed 👍
