### PR TITLE
Deployment fixes for the network path

### LINKED ISSUE #790: Production URL schema breaking contract verification
Our current routes do not allow for relative links on any endpoints which includes contract verification. We need to build in customizable routes to allow for `https://blockscout.com/poa/core`, `https://blockscout.com/poa/sokol`, ect...

These could be environment variables that are defined at deployment.

### PR DESCRIPTION
**Pull request by acravenho**
Fixes #790 

## Motivation

The deployed URL schema should route from subfolders similar to `/poa/sokol` and `/poa/core`. So we are configuring Phoenix to generate links using this `custom/path` that will be configured in the environment.

Notice that, after this configuration, it just generates the link with the `/custom/path` prefixed. But Phoeniex doesn't have a route for that. So, it will be necessary a proxy configuration to strip this `/custom/path` for the URL once the envs are configured, otherwise, the routes never will reach the Phoenix application.

## Changelog

- Adds environment variables for `network`, `subnetwork`, `logo`, `network path`, and `check_origin`.
- Adds the ability to change the `title`, `network path`, `network icon`, and `check_origin` for deployment purposes.
- Refactor the view to use the above variables when they are provided.

### Enhancements
Fixes contract verification in deployment.

### CODE REVIEW

File: apps/block_scout_web/config/config.exs [hunk 1]
```diff
@@ -10,13 +10,27 @@ config :block_scout_web,
   namespace: BlockScoutWeb,
   ecto_repos: [Explorer.Repo]
 
-config :block_scout_web, BlockScoutWeb.Chain, logo: "/images/poa_logo.svg"
+config :block_scout_web, BlockScoutWeb.Chain,
```
Comment (KronicDeth) [inline apps/block_scout_web/config/config.exs]: When you use the same common key (`BlockScoutWeb.Chain`) under the same application (`:block_scout_web`), you don't need to have separate `config` calls and you can collapse this down to

```elixir
config :block_scout_web, BlockScoutWeb.Chain,
  network: System.get_env("NETWORK") || "POA Network",
  subnetwork: System.get_env("SUBNETWORK") || "Sokol Testnet",
  network_icon: System.get_env("NETWORK_ICON") || "_network_icon.html",
  network_path: System.get_env("NETWORK_PATH") || "",
  logo: System.get_env("LOGO") || "/images/poa_logo.svg"
```

File: apps/block_scout_web/lib/block_scout_web/router.ex [hunk 2]
```diff
@@ -15,13 +15,13 @@ defmodule BlockScoutWeb.Router do
     plug(:accepts, ["json"])
   end
 
-  scope "/api/v1", BlockScoutWeb.API.V1, as: :api_v1 do
+  scope Application.get_env(:block_scout_web, BlockScoutWeb.Chain)[:network_path] <> "/api/v1", BlockScoutWeb.API.V1, as: :api_v1 do
```
Comment (KronicDeth) [inline apps/block_scout_web/lib/block_scout_web/router.ex]: I don't think having this router know it is nested under a path like this is the best way to do this.  I don't think it is necessary because you can mount one router under another and it works to get the paths correctly.  @chrismccord what's the correct way to nest the entire Phoenix application under `/poa/core` or `poa/sokol` when deployed?

Comment (chrismccord) [reply apps/block_scout_web/lib/block_scout_web/router.ex]: the endpoint config has a `:path` option that would work perfectly for this, provided *all* routes are nested. If that's the case, the endpoint config is definitely the way to go

Comment (feliperenan) [reply apps/block_scout_web/lib/block_scout_web/router.ex]: Once we have `:path` configured we need to configure the proxy to remove this path for sending the correct route to Phoenix. Otherwise, the user will get `not_found`.

I was playing with it locally using Nginx and I get it working this way:

```Elixir
# config/dev.exs
config :block_scout_web, BlockScoutWeb.Endpoint,
  url: [
    path: "/poa/core"
  ]
```

```nginx
# nginx.conf
server {
    ...
    location / {
        proxy_pass http://127.0.0.1:4000;
    }

    location /poa/core {
        proxy_redirect    off;

        rewrite /poa/core(.*) /$1 break;

        proxy_pass http://127.0.0.1:4000;
    }

    ...
}
```

Do you think it's a good path to follow? 🤔

Comment (chrismccord) [reply apps/block_scout_web/lib/block_scout_web/router.ex]: yes, this is exactly the answer when using nginx :)

File: apps/block_scout_web/config/config.exs (hunk 1 above)
Comment (feliperenan) [reply apps/block_scout_web/config/config.exs]: Here we could just get the env and do the comparison in the view layer. Something like this:

```Elixir
# apps/block_scout_web/config/config.exs
config :block_scout_web, BlockScoutWeb.Chain,
  network: System.get_env("NETWORK"),
  subnetwork: System.get_env("SUBNETWORK"),
  network_icon: System.get_env("NETWORK_ICON"),
  network_path: System.get_env("NETWORK_PATH"),
  logo: System.get_env("LOGO")

# apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
defmodule BlockScoutWeb.LayoutView
  @application_config Application.get_env(:block_scout_web, BlockScoutWeb.Chain)

  def icon_partial do
    Keyword.get(@application_config, :network_icon, "_network_icon.html")
  end

  def logo do
    Keyword.get(@application_config, :logo, "/images/poa_logo.svg")
  end

  def network_title do
    Keyword.get(@application_config, :network, "POA Network")
  end

  def subnetwork_title do
    Keyword.get(@application_config, :subnetwork, "Sokol Testnet")
  end
end
```

@KronicDeth @amandasposito @Lucasnar Does it make sense?

Comment (KronicDeth) [reply apps/block_scout_web/config/config.exs]: Don't capture `Application.get_env` in a module attribute as it means you're not supporting it being runtime configurable.

But otherwise, yes, just checking in the view layer is fine.

File: apps/block_scout_web/lib/block_scout_web/views/layout_view.ex [hunk 3]
```diff
@@ -3,6 +3,28 @@ defmodule BlockScoutWeb.LayoutView do
 
   alias BlockScoutWeb.SocialMedia
 
+  def network_icon_partial do
```
Comment (amandasposito) [inline apps/block_scout_web/lib/block_scout_web/views/layout_view.ex]: Should we test these functions?

Comment (feliperenan) [reply apps/block_scout_web/lib/block_scout_web/views/layout_view.ex]: I think so. I'll try to add it.

Comment (feliperenan) [reply apps/block_scout_web/lib/block_scout_web/views/layout_view.ex]: Done 👍

**Comment by feliperenan** [comment]
@KronicDeth Could you please take a look at it again? I'm the owner of this PR now and I have changed some things here.

File: apps/block_scout_web/lib/block_scout_web/views/layout_view.ex [hunk 4]
```diff
@@ -3,6 +3,28 @@ defmodule BlockScoutWeb.LayoutView do
...
+  end
+
+  def subnetwork_title do
+    Keyword.get(application_config(), :subnetwork) || "Sokol Testnet"
+  end
+
+  def app_title do
+    network_title = Keyword.get(application_config(), :network) || "POA Network"
+
+    subnetwork_title() <> " Explorer - " <> network_title <> " by BlockScout"
```
Comment (KronicDeth) [inline apps/block_scout_web/lib/block_scout_web/views/layout_view.ex]: This needs to pass through `gettext` using a template string as the order of the sentence and works `Explorer` and `by` will need to be translatable.

File: apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs [hunk 5]
```diff
@@ -1,9 +1,80 @@
...
+    end
+
+    test "use the default subnetwork title when there is no env configured for it" do
+      Application.put_env(:block_scout_web, BlockScoutWeb.Chain, network: "Custom Network")
+
+      assert LayoutView.app_title() == "Sokol Testnet Explorer - Custom Network by BlockScout"
+    end
+
+    test "use the default subnetwork and network title when there are no envs configured for they" do
+      assert LayoutView.app_title() == "Sokol Testnet Explorer - POA Network by BlockScout"
```
Comment (KronicDeth) [inline apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs]: This phrasing doesn't really make sense to me I get the first part "Sokol Testnet Explorer", but the "POA Network by BlockScout" makes it sound like "POA Network is a subbrand of BlockScout" like BlockScout is a conglomerate that owns the smaller POA Network company.

Comment (acravenho) [reply apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs]: I agree it does sound kind of awkward. I was keyword stuffing here. I think we should just keep the beginning and maybe add "Blockchain". It should read "Sokol Testnet Blockchain Explorer".

Comment (feliperenan) [reply apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs]: Done! could please you check it again 🙏?
