### PR TITLE
Monitor and shrink memory usage of Sequence and BufferedTasks when soft-limit exceeded

### LINKED ISSUE #888: Clear memory on large chain instances for deferred tasks
On larger chains, the memory consumption can exceed the machines total available memory crashing Erlang. It would be great to be able to clear the memory of async tasks before this occurs.

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #888

### Enhancements
* Add documentation on configuring the `Indexer.Memory.Monitor` soft-limit to the READMEs.
* Don't store `pid` in `%Indexer.BufferedTask{}` and instead get it as needed.
* Instead of queuing up batches, store entries in queue and only form a batch when run is called.  This ensures that the batch size is maximized and previously partial adjacent batches will go out as a full batch.

### Bug Fixes
* `Indexer.Memory.Monitor` checks the total VM memory usage (`:erlang.memory(:total)`) every (1) minute.  If the memory usage exceeds the soft-limit, shrinkable processes are asked to shrink.
  * Memory soft-limit defaults to 1 GiB for safety on laptops, but you'll want to raise this for production deploys @acravenho.  It can be configured with `config :indexer, memory: bytes` with
    * Default set in `apps/indexer/config/config.exs`
    * Default can be per environment like any other config if you'd prefer we ship a higher default for `prod` @acravenho.
* Processes with work queues register themselves as shrinkable with `Indexer.Memory.Monitor`.
  * `:block_catchup_sequence` `Indexer.Sequence`
  * `Indexer.BufferedTask`s

### Incompatible Changes
* `c:Indexer.BufferedTask.run/3` is now `c:Indexer.BufferedTask.run/2` with the `retries` count being removed.  No implementations used the `retries` count and removing it allowed for batching optimizations.
* Remove `Indexer.BufferedTask` `:init_chunk_size` as it didn't really do much besides decided when to send `GenServer.call`s from the `init_task`.

### CODE REVIEW

File: apps/indexer/config/config.exs [hunk 1]
```diff
@@ -2,7 +2,13 @@
 # and its dependencies with the aid of the Mix.Config module.
 use Mix.Config
 
+require Bitwise
```
Comment (zachdaniel) [inline apps/indexer/config/config.exs]: IIRC `import` does a `require` also

File: apps/indexer/lib/indexer/buffered_task.ex [hunk 2]
```diff
@@ -332,73 +358,140 @@ defmodule Indexer.BufferedTask do
...
+        take_batch(new_bound_queue, remaining - 1, [entry | acc])
+
+      {:error, :empty} ->
+        take_batch(bound_queue, 0, acc)
     end
   end
 
-  defp async_perform(entries, dest) do
-    GenServer.call(dest, {:async_perform, entries})
+  # was shrunk and out of work, get more work from `init/2`
```
Comment (zachdaniel) [inline apps/indexer/lib/indexer/buffered_task.ex]: How do we know this was previouslyl shrunk? Does `maximum_size == 0` before any shrinking occurs?

File: apps/indexer/lib/indexer/logger.ex [hunk 3]
```diff
@@ -0,0 +1,15 @@
+defmodule Indexer.Logger do
+  @moduledoc """
+  Appends the PID and its registered name (if it has one) to the `iodata`.
```
Comment (zachdaniel) [inline apps/indexer/lib/indexer/logger.ex]: It seems like the caller is the one adding this to the iodata, so this moduledoc might be out of date.

File: apps/indexer/lib/indexer/buffered_task.ex (hunk 2 above)
Comment (KronicDeth) [reply apps/indexer/lib/indexer/buffered_task.ex]: maximum_size is nil when it's not shrunk

Comment (zachdaniel) [reply apps/indexer/lib/indexer/buffered_task.ex]: Oh, yeah thats what I meant. Unsure why I said zero :)
