### PR TITLE
Fixes for ganache JSON RPC mistakes

### LINKED ISSUE #1290: Can't run blockscout with ganache-cli
Can't run blockscout with ganache-cli

### Environment

* Operating System: OS X 10.14
* Docker 18

### Steps to reproduce

* ganache-cli -v -i 4447 -l='0x7A1200' -g='0x01'
* git clone git@github.com:poanetwork/blockscout.git
* cd blockscout/docker
* COIN=ETH ETHEREUM_JSONRPC_VARIANT=ganache ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545 ETHEREUM_JSONRPC_WEB_SOCKET_URL=ws://host.docker.internal:8545 make start

### Expected behaviour

Chain is indexed

### Actual behaviour

Continuously do the same bunch of 6 eth_getBlockByNumber requests and output error:

```
$ COIN=ETH ETHEREUM_JSONRPC_VARIANT=ganache ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545 ETHEREUM_JSONRPC_WEB_SOCKET_URL=ws://host.docker.internal:8545 make start
==> Checking for blockscout image blockscout_prod
==> Image exist. Using blockscout_prod
==> Checking PostrgeSQL container
==> PostgreSQL Already started
==> Starting blockscout
2019-01-02T14:32:41.123 [warn] The on_load function for module libsecp256k1 returned:
{:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /opt/app/_build/prod/lib/libsecp256k1/priv/libsecp256k1_nif.so: No such file or directory\''}}

2019-01-02T14:32:42.729 application=tzdata [info] tzdata release in place is from a file last modified Thu, 03 May 2018 23:55:14 GMT. Release file on server was last modified Mon, 31 Dec 2018 01:25:12 GMT.
2019-01-02T14:32:43.003 [warn] The on_load function for module libsecp256k1 returned:
{:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /opt/app/_build/prod/lib/libsecp256k1/priv/libsecp256k1_nif.so: No such file or directory\''}}

2019-01-02T14:32:43.695 application=phoenix [info] Running BlockScoutWeb.Endpoint with Cowboy using http://0.0.0.0:4000
2019-01-02T14:32:43.696 application=phoenix [error] Could not find static manifest at "/opt/app/_build/prod/lib/block_scout_web/priv/static/cache_manifest.json". Run "mix phx.digest" after building your static files or remove the configuration from "config/prod.exs".
2019-01-02T14:32:44.105 [error] Task #PID<0.693.0> started from #PID<0.690.0> terminating
** (ArgumentError) Could not convert receipt to elixir

Receipt:
  %{"blockHash" => "0xcdca16fe97759f8a0d7259e0449a7eefb9786e616cbc8d522a408b4e86bb941c", "blockNumber" => "0x1", "contractAddress" => "0x1700797866b2cfaacb8d68fe97715bd284242ba8", "cumulativeGasUsed" => "0x43bd6", "from" => "0x0a4c648677707d5820886252b23c7aead9c9e6a0", "gas" => 8000000, "gasUsed" => "0x43bd6", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "r" => "0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5", "s" => "0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604", "status" => "0x1", "to" => nil, "transactionHash" => "0x0dbd878858dd07b9cb2c6117bc63f36e7a6c1f18adb0e25db3fe2bb993c359e7", "transactionIndex" => "0x0", "v" => "0x1c"}

Errors:
  {:unknown_key, %{key: "v", value: "0x1c"}}
  {:unknown_key, %{key: "s", value: "0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604"}}
  {:unknown_key, %{key: "r", value: "0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5"}}

    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:231: EthereumJSONRPC.Receipt.ok!/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.85414552/1 in Indexer.Block.Fetcher.Receipts.fetch/2>, [[%{block_hash: "0xcdca16fe97759f8a0d7259e0449a7eefb9786e616cbc8d522a408b4e86bb941c", block_number: 1, from_address_hash: "0x0a4c648677707d5820886252b23c7aead9c9e6a0", gas: 8000000, gas_price: 1, hash: "0x0dbd878858dd07b9cb2c6117bc63f36e7a6c1f18adb0e25db3fe2bb993c359e7", index: 0, input: "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102f8806100606000396000f300608060405260043610610062576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630900f01014610067578063445df0ac146100aa5780638da5cb5b146100d5578063fdacd5761461012c575b600080fd5b34801561007357600080fd5b506100a8600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610159565b005b3480156100b657600080fd5b506100bf610241565b6040518082815260200191505060405180910390f35b3480156100e157600080fd5b506100ea610247565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561013857600080fd5b506101576004803603810190808035906020019092919050505061026c565b005b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561023d578190508073ffffffffffffffffffffffffffffffffffffffff1663fdacd5766001546040518263ffffffff167c010000000000000000000000000000000000000000000000000000000002815260040180828152602001915050600060405180830381600087803b15801561022457600080fd5b505af1158015610238573d6000803e3d6000fd5b505050505b5050565b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614156102c957806001819055505b505600a165627a7a72305820ced10989824ed38ed854afb734fbcf2b13ce78d137a4a80720195734c88a6a1e0029", nonce: 0, r: 46178526319110309395694322967997441410857273890441149315080369991027293709477, s: 5899098267950008217509533297317542155180211640379771543908889680054751213060, to_address_hash: nil, transaction_index: 0, v: 28, value: 0}, %{block_hash: "0x75044f5fb8dc6898722b799bd31c07075152516337cf23178ac6c7a99b1c4ba1", block_number: 2, from_address_hash: "0x0a4c648677707d5820886252b23c7aead9c9e6a0", gas: 8000000, gas_price: 1, hash: "0x32401fa121f1d6e073ef7b0074c657e23a2f6b8054d8c682da74e3b7101f8b25", index: 0, input: "0xfdacd5760000000000000000000000000000000000000000000000000000000000000001", nonce: 1, r: 50927051345777419429560223185520269633497428136185627236193002820295952740648, s: 8268841188837516584437269010350603873285981026100656876257861194066732792674, to_address_hash: "0x1700797866b2cfaacb8d68fe97715bd284242ba8", transaction_index: 0, v: 27, value: 0}, %{block_hash: "0x13a1512bbee27a52bac265650d0748cdc3b020b810882e871118a6121c979255", block_number: 3, from_address_hash: "0x0a4c648677707d5820886252b23c7aead9c9e6a0", gas: 8000000, gas_price: 1, hash: "0x84677fdd43d8ddf5bfe1fabdeeda689b3279d1a73fc75e2759cba5f1d0878b58", index: 0, input: "0x608060405234801561001057600080fd5b50610bc8806100206000396000f300608060405260043610610083576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632da28934146100885780634ad71af9146100f157806352da806a1461011e578063b75c7dc614610187578063b7b0fbd1146101b8578063d0d186ae146101e9578063faeba25714610281575b600080fd5b34801561009457600080fd5b506100d3600480360381019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035906020019092919050505061034b565b60405180826000191660001916815260200191505060405180910390f35b3480156100fd57600080fd5b5061011c6004803603810190808035906020019092919050505061037b565b005b34801561012a57600080fd5b50610185600480360381019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035600019169060200190929190803590602001908201803590602001919091929391929390505050610668565b005b34801561019357600080fd5b506101b66004803603810190808035600019169060200190929190505050610749565b005b3480156101c457600080fd5b506101e76004803603810190808035600019169060200190929190505050610823565b005b3480156101f557600080fd5b5061022a600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610907565b6040518080602001828103825283818151815260200191508051906020019060200280838360005b8381101561026d578082015181840152602081019050610252565b505050509050019250505060405180910390f35b34801561028d57600080fd5b506102d0600480360381019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080356000191690602001909291905050506109a1565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156103105780820151818401526020810190506102f5565b50505050905090810190601f16801561033d5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b60006020528160005260406000208181548110151561036657fe5b90600052602060002001600091509150505481565b7ffad0646d0476eaaba9a0e291ca46f1018a02adcadb51fef4c3baf751a8a17ce43382604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a160008060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208054905011151561043357fe5b6000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020805490508110151561047f57fe5b6000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060016000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020805490500381548110151561050e57fe5b90600052602060002001546000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208281548110 (truncated)
2019-01-02T14:32:44.107 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0xcdca16fe97759f8a0d7259e0449a7eefb9786e616cbc8d522a408b4e86bb941c\", \"blockNumber\" => \"0x1\", \"contractAddress\" => \"0x1700797866b2cfaacb8d68fe97715bd284242ba8\", \"cumulativeGasUsed\" => \"0x43bd6\", \"from\" => \"0x0a4c648677707d5820886252b23c7aead9c9e6a0\", \"gas\" => 8000000, \"gasUsed\" => \"0x43bd6\", \"logs\" => [], \"logsBloom\" => \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\", \"r\" => \"0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5\", \"s\" => \"0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604\", \"status\" => \"0x1\", \"to\" => nil, \"transactionHash\" => \"0x0dbd878858dd07b9cb2c6117bc63f36e7a6c1f18adb0e25db3fe2bb993c359e7\", \"transactionIndex\" => \"0x0\", \"v\" => \"0x1c\"}\n\nErrors:\n  {:unknown_key, %{key: \"v\", value: \"0x1c\"}}\n  {:unknown_key, %{key: \"s\", value: \"0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604\"}}\n  {:unknown_key, %{key: \"r\", value: \"0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5\"}}\n"}, [{EthereumJSONRPC.Receipt, :ok!, 2, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 231]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 138]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
2019-01-02T14:32:44.110 [error] GenServer :block_catchup_sequencer terminating
** (ArgumentError) Could not convert receipt to elixir

Receipt:
  %{"blockHash" => "0xcdca16fe97759f8a0d7259e0449a7eefb9786e616cbc8d522a408b4e86bb941c", "blockNumber" => "0x1", "contractAddress" => "0x1700797866b2cfaacb8d68fe97715bd284242ba8", "cumulativeGasUsed" => "0x43bd6", "from" => "0x0a4c648677707d5820886252b23c7aead9c9e6a0", "gas" => 8000000, "gasUsed" => "0x43bd6", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "r" => "0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5", "s" => "0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604", "status" => "0x1", "to" => nil, "transactionHash" => "0x0dbd878858dd07b9cb2c6117bc63f36e7a6c1f18adb0e25db3fe2bb993c359e7", "transactionIndex" => "0x0", "v" => "0x1c"}

Errors:
  {:unknown_key, %{key: "v", value: "0x1c"}}
  {:unknown_key, %{key: "s", value: "0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604"}}
  {:unknown_key, %{key: "r", value: "0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5"}}

    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:231: EthereumJSONRPC.Receipt.ok!/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.672.0>, {%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0xcdca16fe97759f8a0d7259e0449a7eefb9786e616cbc8d522a408b4e86bb941c\", \"blockNumber\" => \"0x1\", \"contractAddress\" => \"0x1700797866b2cfaacb8d68fe97715bd284242ba8\", \"cumulativeGasUsed\" => \"0x43bd6\", \"from\" => \"0x0a4c648677707d5820886252b23c7aead9c9e6a0\", \"gas\" => 8000000, \"gasUsed\" => \"0x43bd6\", \"logs\" => [], \"logsBloom\" => \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\", \"r\" => \"0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5\", \"s\" => \"0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604\", \"status\" => \"0x1\", \"to\" => nil, \"transactionHash\" => \"0x0dbd878858dd07b9cb2c6117bc63f36e7a6c1f18adb0e25db3fe2bb993c359e7\", \"transactionIndex\" => \"0x0\", \"v\" => \"0x1c\"}\n\nErrors:\n  {:unknown_key, %{key: \"v\", value: \"0x1c\"}}\n  {:unknown_key, %{key: \"s\", value: \"0x0d0ac573ca36ae042ba657380ae0c0e8caef8e899465930267c34eaa12423604\"}}\n  {:unknown_key, %{key: \"r\", value: \"0x66181ea28676bcbd94478c717f7a77e36b2afb9cf50e29165541b255230c64a5\"}}\n"}, [{EthereumJSONRPC.Receipt, :ok!, 2, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 231]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 138]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
State: %Indexer.Sequence{bound_queue: %Indexer.BoundQueue{maximum_size: nil, queue: {[], []}, size: 0}, current: nil, step: -10}
```

### PR DESCRIPTION
**Pull request by konstantinzolotarev**
Fixes #1290

## Motivation

After last `ganache` release their JSON RPC changed and new fields with non documented values appeared.

### Enhancements
- Ignoring `r,s,v` fields into transaction receipt parsing.

### Bug Fixes
- `r,s,v` fields with `null` values now will decode to correct `r: 0` for transaction parsing instead of

  ```
  ** (ArgumentError) Could not convert receipt to elixir

  Errors:
    {:unknown_key, %{key: "v", value: "0x1c"}}
    {:unknown_key, %{key: "s", value: "0x"}}
    {:unknown_key, %{key: "r", value: "0x"}}
  ```

### CODE REVIEW

File: apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex [hunk 1]
```diff
@@ -311,6 +311,11 @@ defmodule EthereumJSONRPC.Transaction do
     {key, quantity_to_integer(quantity)}
   end
 
+  # as always ganache has it's own vision on JSON RPC standard
+  defp entry_to_elixir({key, quantity}) when key in ~w(r s v) and quantity == nil do
```
Comment (KronicDeth) [inline apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex]:
```suggestion
  defp entry_to_elixir({key, nil}) when key in ~w(r s v) do
```

Don't use a variable and guard `when variable == value` for a fixed `value`.  Match it directly in the pattern.

**Comment by acravenho** [comment]
Thank you @konstantinzolotarev
