### PR TITLE
fix: add fields for contract filter performance

### LINKED ISSUE #1951: Listing of not-yet-decompiled contracts seems to stall with 504/502 occasionally
On the current staging server, going to:

/api?module=contract&action=listcontracts&offset=100&page=0&filter=4

Seems to produce 502/504 right now, and for the past 2 hours. We are retrying connection once every 10s, and sometimes it goes through, but most often it does not.

By the way:
- offset - this is really 'limit', right?

- is there an upper reasonable limit of returned entries? we're grabbing the batches of 10k contracts, but would not want to stress your database

### PR DESCRIPTION
**Pull request by zachdaniel**
Resolves #1951

### Bug Fixes
* Due to poor performance with the filters for not decompiled and not verified smart contracts in the JSON RPC, this adds supporting fields on addresses to signify decompiled/verified contract addresses.
* Adds a Temporary fetcher that will backfill the old data.

### Incompatible Changes
* For performance reasons, I had to remove the "DecompilerVersion" attribute from the API response for listing contracts. I can add it back in if necessary, but things will become much slower. Since this was a new API endpoint, I don't think it would be too bad to remove that field. Let me know.

## Checklist for your PR

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so if necessary

### CODE REVIEW

File: apps/explorer/lib/explorer/chain.ex [hunk 1]
```diff
@@ -536,9 +536,19 @@ defmodule Explorer.Chain do
...
-    |> DecompiledSmartContract.changeset(attrs)
-    |> Repo.insert(on_conflict: :replace_all, conflict_target: [:decompiler_version, :address_hash])
+    changeset = DecompiledSmartContract.changeset(%DecompiledSmartContract{}, attrs)
+
+    Multi.new()
+    |> Multi.insert(:decompiled_smart_contract, changeset,
+      on_conflict: :replace_all,
+      conflict_target: [:decompiler_version, :address_hash]
+    )
+    |> Multi.run(:set_address_decompiled, &set_address_decompiled/2)
```
Comment (ayrat555) [inline apps/explorer/lib/explorer/chain.ex]: it would be great if we added a test for this update

File: apps/explorer/lib/explorer/chain.ex [hunk 2]
```diff
@@ -2215,13 +2225,43 @@ defmodule Explorer.Chain do
       |> Multi.insert(:smart_contract, smart_contract_changeset)
       |> Multi.run(:clear_primary_address_names, &clear_primary_address_names/2)
       |> Multi.run(:insert_address_name, &create_address_name/2)
+      |> Multi.run(:set_address_verified, &set_address_verified/2)
```
Comment (ayrat555) [inline apps/explorer/lib/explorer/chain.ex]: it would be great if we added a test for this update

File: apps/indexer/lib/indexer/temporary/mark_decompiled_and_verified_smart_contracts.ex [hunk 3]
```diff
@@ -0,0 +1,98 @@
+defmodule Indexer.Temporary.MarkDecompiledAndVerifiedSmartContracts do
```
Comment (ayrat555) [inline apps/indexer/lib/indexer/temporary/mark_decompiled_and_verified_smart_contracts.ex]: tests?

File: apps/explorer/lib/explorer/chain.ex [hunk 4]
```diff
@@ -2215,13 +2225,43 @@ defmodule Explorer.Chain do
...
+  end
+
+  defp set_address_verified(repo, %{smart_contract: %SmartContract{address_hash: address_hash}}) do
+    query =
+      from(
+        address in Address,
+        where: address.hash == ^address_hash
+      )
+
+    case repo.update_all(query, set: [verified: true]) do
```
Comment (pasqu4le) [inline apps/explorer/lib/explorer/chain.ex]: Just curious: why not something like: `Address |> repo.get!(address_hash) |> Address.changeset(%{verified: true}) |> repo.update()`?

File: apps/explorer/lib/explorer/chain.ex [hunk 5]
```diff
@@ -2734,58 +2774,54 @@ defmodule Explorer.Chain do
...
-        where:
-          fragment(
-            "EXISTS (SELECT 1 FROM decompiled_smart_contracts WHERE decompiled_smart_contracts.address_hash = ?)",
-            address.hash
-          ),
-        preload: [:decompiled_smart_contracts, :smart_contract],
-        order_by: [asc: address.inserted_at],
+        where: address.contract_code != <<>>,
+        where: not is_nil(address.contract_code),
+        where: fragment("? IS TRUE", address.decompiled),
```
Comment (pasqu4le) [inline apps/explorer/lib/explorer/chain.ex]: no need for a `fragment` here `address.decompiled == true` should be fine

Comment (zachdaniel) [reply apps/explorer/lib/explorer/chain.ex]: Ah, yeah I need it for the `IS NOT TRUE` ones, to catch `NULL`, but not here, you are correct.

File: apps/explorer/lib/explorer/chain.ex (hunk 4 above)
Comment (zachdaniel) [reply apps/explorer/lib/explorer/chain.ex]: It operates on a batch at a time, so it is much faster to issue one update for all of them instead of iterating and updating.

File: apps/explorer/lib/explorer/chain.ex (hunk 2 above)
Comment (zachdaniel) [reply apps/explorer/lib/explorer/chain.ex]: Added a test for this update.

**Comment by zachdaniel** [comment]
@vbaranov Alright, I removed the temporary fetcher from this PR, so that it can safely be merged. I also double checked, and the data is fully migrated. There are no decompiled_smart_contracts that aren't marked as `decompiled=TRUE` in the address table, and all decompiled_smart_contracts are marked as `imported=TRUE`. When we're sure we are done with it, we can drop the `imported` field from `decompiled_smart_contracts`.

File: apps/explorer/lib/explorer/chain.ex (hunk 1 above)
Comment (zachdaniel) [reply apps/explorer/lib/explorer/chain.ex]: Added a test for this.
