### PR TITLE
fix: use better queries for listLogs endpoint

### LINKED ISSUE #1858: getLogs blockscout API does not work
As soon as call `getLogs` by the GET request it returns `Gateway time-out`

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): N/A
* Operating System: Linux

### Steps to reproduce

Tried this both through the BlockScout web interface and in the CLI. In both cases cannot get the list of events. Here is example of the request:
```
curl -X GET "https://blockscout.com/eth/mainnet/api?module=logs&action=getLogs&fromBlock=6478422&toBlock=6478678&address=0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359" -H "accept: application/json"
```

### Expected behaviour

The list of the events raised by the contract.
For example if I run the JSON RPC towards an Infura endpoint with the same block range:
```
curl --data '{"method":"eth_getLogs","params":[{"fromBlock":"0x62da56","toBlock":"0x62db56","address":"0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://mainnet.infura.io
```
it returns the list of logs.

### Actual behaviour

```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>blockscout.com | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<script src="/cdn-cgi/apps/head/1ltfbm2t11oNotCVyOb2mff_fKk.js"></script><link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type">Error</span>
<span class="cf-error-code">504</span>
<small class="heading-ray-id">Ray ID: 4cf2dc7ffc4375be &bull; 2019-04-29 17:05:57 UTC</small>
</h1>
<h2 class="cf-subheadline">Gateway time-out</h2>
</div>
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">You</span>
<h3 class="cf-status-name">Browser</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">Stockholm</span>
<h3 class="cf-status-name">Cloudflare</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc">blockscout.com</span>
<h3 class="cf-status-name">Host</h3>
<span class="cf-status-label">Error</span>
</div>
</div>
</div>
</div>
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2>What happened?</h2>
<p>The web server reported a gateway time-out error.</p>
</div>
<div class="cf-column">
<h2>What can I do?</h2>
<p>Please try again in a few minutes.</p>
</div>
</div>
</div>
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>4cf2dc7ffc4375be</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Your IP</span>: 188.130.155.155</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by zachdaniel**
#1858 

## Motivation

* The listLogs api endpoint is very slow for moderate-large block ranges. The queries that this PR replaces would take about 500 seconds. These ones still aren't *that* fast, but they complete in 15-30 seconds for those same block ranges so it is a vast improvement.

### Bug Fixes
* Use a more optimized query when provided with an address hash filter. We first limit our search to logs from transactions and internal transactions that were from, to, or creating the provided address. This limits the search space significantly.

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so if necessary

Note: The existing tests reinforce correct behavior, but I can't write a unit test to confirm the performance characteristics.

### CODE REVIEW

File: apps/explorer/lib/explorer/etherscan/logs.ex [hunk 1]
```diff
@@ -67,33 +67,99 @@ defmodule Explorer.Etherscan.Logs do
...
+    all_transaction_logs_query =
+      from(transaction in Transaction,
+        join: log in ^logs_query,
+        on: log.transaction_hash == transaction.hash,
+        where: transaction.block_number >= ^prepared_filter.from_block,
+        where: transaction.block_number <= ^prepared_filter.to_block,
+        where: transaction.to_address_hash == ^address_hash,
+        or_where: transaction.from_address_hash == ^address_hash,
+        or_where: transaction.created_contract_address_hash == ^address_hash,
+        select:
```
Comment (pasqu4le) [inline apps/explorer/lib/explorer/etherscan/logs.ex]: This is only my opinion, but I think this and the previous `select` would be more readable by also using `select_merge`, in this case:
```
select: map(log, ^@log_fields),
select_merge: map(transaction, [:gas_price, :gas_used, :block_number]),
select_merge: %{transaction_index: transaction.index}
```

File: apps/explorer/lib/explorer/etherscan/logs.ex [hunk 2]
```diff
@@ -67,33 +67,99 @@ defmodule Explorer.Etherscan.Logs do
...
+    prepared_filter = Map.merge(@base_filter, filter)
+
+    logs_query = where_topic_match(Log, prepared_filter)
+
+    block_transaction_query =
+      from(transaction in Transaction,
+        join: block in assoc(transaction, :block),
+        on: block.number >= ^prepared_filter.from_block,
+        on: block.number <= ^prepared_filter.to_block,
+        on: block.consensus == true,
```
Comment (pasqu4le) [inline apps/explorer/lib/explorer/etherscan/logs.ex]: Just a nitpick: AFAIK specifying this constraints in `on` or `where` is indifferent as far as the actual plan that postgresql produces, but I'd argue that it is better to use `where` when it does not have strictly to do with how the two tables are `join`ed.
If not else at least for consistency, you did in fact use `where` in this cases in all the other queries (except for another `on: block.consensus == true`)

File: apps/explorer/lib/explorer/etherscan/logs.ex [hunk 3]
```diff
@@ -67,33 +67,99 @@ defmodule Explorer.Etherscan.Logs do
...
+        select_merge: %{
+          block_timestamp: block.timestamp
+        }
+      )
+
+    Repo.all(query_with_blocks)
+  end
+
+  # Since address_hash was not present, we know that a
+  # topic filter has been applied, and th
```
[the remark this answers is not in the document]
Comment (zachdaniel) [reply apps/explorer/lib/explorer/etherscan/logs.ex]: Oops :)
