### PR TITLE
fix skipped feature tests

### LINKED ISSUE #1136: Feature tests are failing when using ajax
The project is currently using the `wallaby` lib with `phantomjs` driver in the feature tests.

When changing the pages to use async load using ajax, a few tests started to fail with no apparent reason. Some tests were moved to controller tests and the ones that were worth keeping are marked with a `skip` tag.

This may be happening because the `phantomjs` [is no longer being developed](http://phantomjs.org), and it may be necessary to change the driver to use the headless chrome. Or because `wallaby` itself [it is not being actively maintained](https://keathley.io/elixir/wallaby/2018/08/10/wallaby-is-looking-for-new-maintainers.html).

### PR DESCRIPTION
**Pull request by GuSilverFlame**
closes #1136

### Enhancements
* make address internal transactions use redux with the async load

### Bug Fixes
* make tests that are being skipped work again
* unskip those tests
* have address internal transactions work real time again(one of the tests depended on it)

### CODE REVIEW

File: apps/block_scout_web/assets/__tests__/pages/address/internal_transactions.js [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+      items: ['test 1']
+    })
+    const action = {
+      type: 'RECEIVED_NEW_INTERNAL_TRANSACTION_BATCH',
+      msgs: [{ internalTransactionHtml: 'test 2' }]
+    }
+    const output = reducer(state, action)
+
+    expect(output.items).toEqual(['test 2', 'test 1'])
+  })
```
Comment (feliperenan) [inline apps/block_scout_web/assets/__tests__/pages/address/internal_transactions.js]: 🎨 I would add a blank line between each test as we do in the Elixir code.

File: apps/block_scout_web/assets/js/pages/address.js [hunk 2]
```diff
@@ -22,9 +18,6 @@ export const initialState = {
   transactionCount: null,
   validationCount: null,
 
-  internalTransactions: [],
-  internalTransactionsBatch: [],
-  validatedBlocks: [],
   beyondPageOne: false
```
Comment (feliperenan) [inline apps/block_scout_web/assets/js/pages/address.js]: There is no need this state anymore since all tabs (transactions, internal transactions, etc..) now have their own redux. Also, you can remove any logic that is depending on this state in this file.

File: apps/block_scout_web/assets/js/pages/address/internal_transactions.js [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+import socket from '../../socket'
+import { batchChannel } from '../../lib/utils'
+import { connectElements } from '../../lib/redux_helpers.js'
+import { createAsyncLoadStore } from '../../lib/async_listing_load'
+
+const BATCH_THRESHOLD = 10
+
+export const initialState = {
+  channelDisconnected: false,
+
```
Comment (feliperenan) [inline apps/block_scout_web/assets/js/pages/address/internal_transactions.js]: 🎨 I think we can ✂️ this blank lines in this state.

File: apps/block_scout_web/assets/__tests__/pages/address/internal_transactions.js [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+    const action = {
+      type: 'RECEIVED_NEW_INTERNAL_TRANSACTION_BATCH',
+      msgs: [{ internalTransactionHtml: 'test 2' }]
+    }
+    const output = reducer(state, action)
+
+    expect(output.items).toEqual(['test 1'])
+  })
+
+  test('with filtered out internal transaction', () => {
```
Comment (feliperenan) [inline apps/block_scout_web/assets/__tests__/pages/address/internal_transactions.js]: We could add more tests to cover all filter scenarios. Here a similar one that you can use as a base:

https://github.com/poanetwork/blockscout/blob/9d620f253079dc10947458c590961c66393bd71e/apps/block_scout_web/assets/__tests__/pages/address/transactions.js#L45
