### PR TITLE
Fix Address Trasaction query

### LINKED ISSUE #1183: Token Transfers on an address transactions page not showing up
When a token is sent, the **recipient (to)** address of the token transfer is not seeing the token transfer on the transactions tab. Here is an example below:

Token: Hello
From: 0x01
To: 0x02

The token transfer is showing up on the `0x01` transaction tab, but the token transfer is not showing up on `0x02`.

### PR DESCRIPTION
**Pull request by amandasposito**
Resolves #1183

The `address` `transaction` listing (with an `address`  that has 7MM `transactions`) is loading within 7s using a db similar to the ethereum mainnet.

screen shot 2018-12-11 at 17 27 39

Normal addresses continue to load quickly as well

screen shot 2018-12-11 at 17 28 28

## Motivation

When a token is sent, the recipient (to) address of the token transfer is not seeing the token transfer on the transactions tab. 

### Bug Fixes

* The bug was that only the first transaction that had token transfers was being shown.

### CODE REVIEW

**Comment by acravenho** [comment]
Does this change our performance on Mainnet?

**Comment by amandasposito** [comment]
@acravenho I tested using the db test, with this [address](https://etherscan.io/address/0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0) and it loaded the listing within 8s ~ 6s

File: apps/explorer/test/explorer/chain_test.exs [hunk 1]
```diff
@@ -271,6 +271,56 @@ defmodule Explorer.ChainTest do
       assert Enum.count(transaction.token_transfers) == 2
     end
 
+    test "returns all transactions that the address is present only in the token transfers from_address" do
```
Comment (feliperenan) [inline apps/explorer/test/explorer/chain_test.exs]: ❤️

File: apps/explorer/test/explorer/chain/token_transfer_test.exs [hunk 2]
```diff
@@ -251,4 +251,184 @@ defmodule Explorer.Chain.TokenTransferTest do
       assert results == []
     end
   end
+
+  describe "where_any_address_fields_match/3" do
+    test "when to_address_hash match returns transactions hashes list" do
```
Comment (feliperenan) [inline apps/explorer/test/explorer/chain/token_transfer_test.exs]: Wdyt of `returns the transactions hashes when the to_address_hash from the token transfers match`.

File: apps/explorer/test/explorer/chain/token_transfer_test.exs [hunk 3]
```diff
@@ -251,4 +251,184 @@ defmodule Explorer.Chain.TokenTransferTest do
...
+        transaction: transaction_one,
+        amount: 1
+      )
+
+      transactions_hashes = TokenTransfer.where_any_address_fields_match(:to, paul.hash, %PagingOptions{page_size: 1})
+
+      assert Enum.member?(transactions_hashes, transaction_one.hash) == true
+    end
+
+    test "when from_address_hash match returns transactions hashes list" do
```
Comment (feliperenan) [inline apps/explorer/test/explorer/chain/token_transfer_test.exs]: Wdyt of `returns the transactions hashes when the from_address_hash from the token transfers match`.

File: apps/explorer/test/explorer/chain/token_transfer_test.exs [hunk 4]
```diff
@@ -251,4 +251,184 @@ defmodule Explorer.Chain.TokenTransferTest do
...
+      john = insert(:address)
+      paul = insert(:address)
+      contract_address = insert(:contract_address)
+
+      transaction_one =
```
Comment (feliperenan) [inline apps/explorer/test/explorer/chain/token_transfer_test.exs]: 🎨 I would call it transaction since there is no other transaction in this test.

File: apps/explorer/test/explorer/chain/token_transfer_test.exs (hunk 2 above)
Comment (amandasposito) [reply apps/explorer/test/explorer/chain/token_transfer_test.exs]: IMO I think it is better to have what is being tested at the start of the phrase.

File: apps/explorer/test/explorer/chain/token_transfer_test.exs (hunk 3 above)
Comment (amandasposito) [reply apps/explorer/test/explorer/chain/token_transfer_test.exs]: IMO I think it is better to have what is being tested at the start of the phrase.

File: apps/explorer/test/explorer/chain/token_transfer_test.exs (hunk 2 above)
Comment (amandasposito) [reply apps/explorer/test/explorer/chain/token_transfer_test.exs]: 🤔 

I believe that since this is the `token_transfers` file test it wouldn't be that necessary.

Comment (feliperenan) [reply apps/explorer/test/explorer/chain/token_transfer_test.exs]: Oh sorry, I didn't see that we were in the `token_tranfers` file :/.
