### PR TITLE
Fix constructor arguments migration

### LINKED ISSUE #1442: (Postgrex.Error) ERROR 42703 (undefined_column) column s0.constructor_arguments does not exist
Might there be a missing migration after today's merges?   Yesterday's master branch was fine, but today's is broken:

```
(Postgrex.Error) ERROR 42703 (undefined_column) column s0.constructor_arguments does not exist
```
query: SELECT s0."id", s0."name", s0."compiler_version", s0."optimization", s0."contract_source_code", s0."constructor_arguments", s0."abi", s0."address_hash", s0."inserted_at", s0."updated_at", s0."address_hash" FROM "smart_contracts" AS s0 WHERE (s0."address_hash" = $1)
```
     (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
     (ecto_sql) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute/5
     (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
     (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
     (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
 Last message: :update_tokens
 State: %{update_interval: 7}

```

### Environment

I am using `make start` to build and run the docker container defined by `docker/Dockerfile`

### PR DESCRIPTION
**Pull request by acravenho**
Fixes #1442 

## Motivation

This PR fixes an issue where a PR was merged that included a migration that was dated prior to migrations that have already occurred. 

## Changelog

- Drops `constructor_arguments` column from the `smart_contracts` table if it exists.
- Adds the `constructor_arguments` column to `smart_contracts` table

### CODE REVIEW

File: apps/explorer/priv/repo/migrations/20190213105501_add_constructor_arguments_to_smart_contracts.exs [hunk 1]
```diff
@@ -1,6 +1,11 @@
 defmodule Explorer.Repo.Migrations.AddConstructorArgumentsToSmartContracts do
   use Ecto.Migration
 
+  def up do
+    # Check for the existence of constructor arguments and remove
+    execute("ALTER TABLE smart_contracts DROP COLUMN IF EXISTS constructor_arguments")
+  end
+
   def change do
```
Comment (ayrat555) [inline apps/explorer/priv/repo/migrations/20190213105501_add_constructor_arguments_to_smart_contracts.exs]: should this method be deleted?

Comment (zachdaniel) [reply apps/explorer/priv/repo/migrations/20190213105501_add_constructor_arguments_to_smart_contracts.exs]: I think we just want to rename `change/0` to `down/0` (and we should make sure to test the down as well)

Comment (zachdaniel) [reply apps/explorer/priv/repo/migrations/20190213105501_add_constructor_arguments_to_smart_contracts.exs]: by test, I just mean roll it back and make sure it works once :D

Comment (acravenho) [reply apps/explorer/priv/repo/migrations/20190213105501_add_constructor_arguments_to_smart_contracts.exs]: If that `DROP COLUMN IF EXISTS` is not included then people who ran the migration successfully will cause an error due to the column already existing.

Comment (acravenho) [reply apps/explorer/priv/repo/migrations/20190213105501_add_constructor_arguments_to_smart_contracts.exs]: `down/0` is not working. `change/0` is the only thing that works here. I'm open to any other thoughts here.
