### PR TITLE
Partial retry for batched JSONRPC requests

### LINKED ISSUE #1070: Optimize error handling for batches
Currently, when an error occurs during the indexing process, the entire batch is canceled and retried at a later time. This optimization will allow successful parts of a batch to continue while retrying only the parts of the batch that failed.

### PR DESCRIPTION
**Pull request by KronicDeth**
Resolves #1070

### Enhancements
* Partial retry for batched JSONRPC requests
  * Any `EthereumJSONRPC` function that did batch request now return a struct that contains both the successfully decoded params and any fetch errors, so that the caller can decide what to do instead of deferring to any errors as happened before.
  * `Indexer.CoinBalance.Fetcher` will retry only those balances that can't be fetched.
  * `Indexer.Block.Uncle.Fetcher` will retry only those hashes that can't be fetched.
  * `Indexer.Block.Catchup.Fetcher` will retry only those numbers that can't be fetched.
  * `Indexer.Block.Realtime.Fetcher` has no retry mechanism since it defers to `Indexer.Block.Catchup.Fetcher`, so it will not change.

### CODE REVIEW

File: apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex [hunk 1]
```diff
@@ -68,6 +68,25 @@ defmodule EthereumJSONRPC.Block do
...
   @type t :: %{String.t() => EthereumJSONRPC.data() | EthereumJSONRPC.hash() | EthereumJSONRPC.quantity() | nil}
 
+  def from_response(%{id: id, result: nil}, id_to_params) when is_map(id_to_params) do
+    params = Map.fetch!(id_to_params, id)
+
+    {:error, %{code: 404, message: "Not Found", data: params}}
+  end
+
+  def from_response(%{id: id, result: block}, id_to_params) when is_map(id_to_params) do
+    true = Map.has_key?(id_to_params, id)
```
Comment (sabondano) [inline apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex]: We want to blow up here vs. returning an error?

Comment (KronicDeth) [reply apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex]: We want it to blow up.  This should only happen if the server's implementation has an error and it sends back an `id` we don't expect.  We protect this case in all clauses, but in most cases this is a `Map.fetch!` because we care about the params as in the `error` case on line 72.  For here we can't care about the params, so `has_key?` is cheaper.
